# Generated by Django 3.0.5 on 2020-06-15 22:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('choices', '0002_title'),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='poodle',
            name='titles_prefix',
            field=models.ManyToManyField(blank=True, related_name='poodles_prefix', to='choices.Title', verbose_name='Prefix Titles'),
        ),
        migrations.AddField(
            model_name='poodle',
            name='titles_suffix',
            field=models.ManyToManyField(blank=True, related_name='poodles_suffix', to='choices.Title', verbose_name='Suffix Titles'),
        ),
        migrations.CreateModel(
            name='HealthClearance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, verbose_name='Clearance')),
                ('result', models.CharField(blank=True, default='', max_length=50, verbose_name='Result')),
                ('is_viewable', models.BooleanField(default=True, verbose_name='Viewable?')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('poodle', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='poodles_health', to='core.Poodle', verbose_name='Poodle')),
            ],
        ),
    ]
