# Generated by Django 3.0.5 on 2020-06-28 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20200615_2216'),
    ]

    operations = [
        migrations.AddField(
            model_name='healthclearance',
            name='ofa_num',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='OFA #'),
        ),
        migrations.AlterField(
            model_name='healthclearance',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Clearance'),
        ),
        migrations.AlterField(
            model_name='healthclearance',
            name='result',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Result'),
        ),
    ]
