# Generated by Django 3.0.5 on 2020-07-08 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20200628_2145'),
    ]

    operations = [
        migrations.AddField(
            model_name='poodle',
            name='ofa_url',
            field=models.URLField(blank=True, default='', max_length=300, null=True, verbose_name='OFA URL'),
        ),
        migrations.DeleteModel(
            name='HealthClearance',
        ),
    ]
