# Generated by Django 3.0.5 on 2020-06-15 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('choices', '0003_title_kennel_club'),
    ]

    operations = [
        migrations.AddField(
            model_name='title',
            name='full',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Full'),
        ),
        migrations.AlterField(
            model_name='title',
            name='abbr',
            field=models.CharField(max_length=5, unique=True, verbose_name='Abbreviation'),
        ),
    ]
