# Generated by Django 3.0.5 on 2020-06-15 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('choices', '0004_auto_20200615_2226'),
    ]

    operations = [
        migrations.AlterField(
            model_name='title',
            name='kennel_club',
            field=models.CharField(blank=True, choices=[('AKC', 'American Kennel Club'), ('UKC', 'United Kennel Club'), ('CKC', 'Canadian Kennel Club'), ('FCI', 'Fédération Cynologique Internationale'), ('U', 'Unknown')], max_length=4, null=True, verbose_name='Kennel Club'),
        ),
        migrations.AlterField(
            model_name='title',
            name='sport',
            field=models.CharField(blank=True, choices=[('C', 'Conformation'), ('A', 'Agility'), ('O', 'Obedience'), ('P', 'Performance'), ('U', 'Unknown')], max_length=50, null=True, verbose_name='Sport'),
        ),
    ]
