# Generated by Django 3.0.5 on 2020-06-15 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('choices', '0005_auto_20200615_2232'),
    ]

    operations = [
        migrations.AlterField(
            model_name='title',
            name='abbr',
            field=models.CharField(max_length=10, unique=True, verbose_name='Abbreviation'),
        ),
    ]
